version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - commit=docker-dompose
    ports:
      - "8080:8080"
    environment:
      WEB_ENABLED: true
      WORKER_ENABLED: false