version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - commit=docker-dompose
    ports:
      - "8080:8080"
    environment:
      WEB_ENABLED: true
      WORKER_ENABLED: false
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      VERBOSITY: 4
      SESSION_KEY: compose

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'

    volumes: 
      - redis:/data
volumes:
  redis:
