name: CD
on:
  push:
    branches:
    - main
  pull_request: # to
    branches:   # be
    - main      # removed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nu12/audio-gonverter:workflow
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/nu12/audio-gonverter:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/nu12/audio-gonverter:${{ github.sha }}
        format: 'sarif'
        output: 'image.sarif'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload trivy results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'image.sarif'
        category: image