name: CD
on:
  push:
    branches:
    - main
  pull_request: # to
    branches:   # be
    - main      # removed

jobs:
  release:
    outputs:
      next: ${{steps.release.outputs.next}}
      current: ${{steps.release.outputs.current}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.6
    
    - name: Bump version
      id: release
      run: |
        go install github.com/caarlos0/svu@latest
        CURRENT=$(svu c)
        NEXT=$(svu n)

        echo "current=$CURRENT" >> $GITHUB_OUTPUT
        echo "next=$NEXT" >> $GITHUB_OUTPUT
        echo "$CURRENT/$NEXT" >> $GITHUB_STEP_SUMMARY

    - name: Create GH release
      if: steps.release.outputs.next != steps.release.outputs.current
      env:
        TAG: ${{steps.release.outputs.next}}
        GH_TOKEN: ${{ github.TOKEN }}
      run: |
        git tag $TAG
        git push --tags

        gh release create $TAG

  build:
    runs-on: ubuntu-latest
    needs: [release]
    if: needs.release.outputs.next != needs.release.outputs.current
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/nu12/audio-gonverter:latest,ghcr.io/nu12/audio-gonverter:${{ needs.release.outputs.next }}

  analysis:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Pull latest image
      run: |
        docker pull ghcr.io/nu12/audio-gonverter:latest
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/nu12/audio-gonverter:latest
        format: 'sarif'
        output: 'image.sarif'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Upload trivy results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'image.sarif'
        category: image