name: CD
on:
  push:
    branches:
    - main
  pull_request: # to
    branches:   # be
    - main      # removed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    
    - name: Create release
      uses: go-semantic-release/action@v1
      id: release
      with:
        github-token: ${{ secrets.TOKEN }}
        force-bump-patch-version: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/nu12/audio-gonverter:latest,ghcr.io/nu12/audio-gonverter:${{ steps.release.outputs.version }}

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     input: image.tar
    #     format: 'sarif'
    #     output: 'image.sarif'
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'

    # - name: Upload trivy results
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: 'image.sarif'
    #     category: image