name: CI
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: |
        gofmt -d cmd/* | tee -a fmt
        if [ ! -s fmt ]
        then
          echo "Code not well formated. See pre-commit hook in README."
          exit 1
        fi
    - name: Run tests
      run: |
        go test -v cmd/*
