name: CI
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nu12/audio-gonverter:workflow
    steps:
    - uses: actions/checkout@v3
    - name: Check format
      run: |
        gofmt -d cmd/* | tee -a fmt
        if [ "$(cat fmt)" != "" ]
        then
          echo "Code not well formated. See pre-commit hook in README."
          exit 1
        fi
    - name: Run tests
      run: |
        go test -v cmd/*.go

    - name: Build image
      run: |
        docker build -t ghcr.io/nu12/audio-gonverter:${{ github.sha }} .

    - name: Run trivy
      run: |
        trivy image ghcr.io/nu12/audio-gonverter:${{ github.sha }} --format sarif --output image.sarif

    - name: Upload trivy results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'image.sarif'
        category: image
